### ISSUE TITLE
[Feature] Allow rendering to multiple ThreeJS scenes

### ISSUE THREAD

**Issue by solvedDev** [JannisX11/wintersky#4]
## Problem
bridge. has a split-screen mode that allows previewing two particle effects simultaneously. Currently, Wintersky doesn't support rendering emitters to two different ThreeJS scenes because the important `Wintersky.space` variable can only be set globally.
I tried switching the space variable out before starting the emitter but the `Emitter.tick()` function calls `Emitter.start()` internally so this breaks in `loop` mode too.

## Proposed Solution
There are two possible ways I could see this being solved:
1) Turn Wintersky into a class so users can create a new instance of the class containing all relevant state
```javascript
import { Wintersky, Emitter } from "wintersky"

const wintersky = new Wintersky({ space: myEmitterSpace })
// Creating an emitter...
const emitter = new Emitter(wintersky, config, options)
```

2) Allow passing a `space` property when creating a new Emitter
```javascript
new Wintersky.Emitter(config, { space: myEmitterSpace })
```

## Additional Notes
I can implement the solution you prefer if you see this as a suitable addition to Wintersky.

**Comment by JannisX11** [comment]
I think turning it into a class would be the best solution. That would also future proof it for other scene-based properties, like event driven auxiliary paticle emitters.

I would make the Wintersky class the default export and make Emitters etc. static properties on that class. Otherwise it would end up with redundant names like `new Wintersky.Wintersky()` when using the UMD bundle. Another solution would be to call it `Scene`, but I do like the Wintersky name for the class.

But yeah, feel free to implement this!
